name: backend app CI process
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo to runner
        uses: actions/checkout@v5
      - name: Read app version from package.json
        run: |
          version=$( jq -r .version package.json)
          echo "appVersion=$version" >> $GITHUB_ENV
      - name: Display app version
        run: |
          echo "backend app version is: ${{ env.appVersion }}"
      - name: install dependency
        run: npm install

         

        
