name: backend
on: 
  workflow_dispatch:
env:
  appVersion: ""
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: display files
        run: |
          ls -l
      - name: read app version
        run: |
          # Use jq to parse version and save to $GITHUB_ENV
          echo "appVersion=$(jq -r .version package.json)" >> $GITHUB_ENV

        
