on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello..${{ inputs.name}} age ${{ inputs.age }}"


