name: Test
on: 
  workflow_dispatch:
    inputs:
      proceed:
        description: 'Proceed?'
        required: true
        type: choice
        options:
          - Yes
          - No
jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.proceed == 'Yes'}}
    steps:
      - run: echo "This job executed after approvals"